language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "Tests"
      name: "Lint check"
      script: yarn lint
    - script: yarn test
      name: "Unit tests"
    - stage: "Build"
      script: yarn build
